name: Continuous Integration 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Python Lint Code Scanning Action
        usos: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
        linter: pyLint